#!/bin/sh

case "$1" in
  start)
    echo "Loading SPI modules..."
    /sbin/modprobe spi-bcm2835
    /sbin/modprobe spidev
    echo "SPI modules loaded"
    ;;
  stop)
    # Nothing to do when stopping
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
